version: "3.9"

services:
  nodpt-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodpt-ai:latest
    container_name: nodpt-ai
    ports:
      - "8000:8000"
    restart: always
